name: Build MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up script permissions
      run: chmod +x ./setup_macos.sh
    - name: install dependencies
      run: ./setup_macos.sh
    - name: make
      run: make
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/